### ISSUE TITLE
Timings Graphics in browser not working

### ISSUE THREAD

**Issue by RainOfPain125** [aikar/timings#65]
![image](https://user-images.githubusercontent.com/33137905/47327244-738f0480-d63a-11e8-8a15-e378d39a9766.png)

I am running Thermos 1.7.10 for the FTB Infinity Evolved Modpack

I installed thermos specifically so I could put 1-2 plugins and run some timings. The timings are printed out in the .txt just fine but when doing /timings paste or /timings report and using the provided link gives the image shown. Is this a bug? What's going wrong?

I can do timings just fine on my vanilla 1.12 server. Though this is obviously different, and is also on a VPS.

**Comment by electronicboy** [comment]
Aikar no longer supports v1 timings due to spigot moving them from his site, you can use this to patch it back up on an unsupported version: https://www.spigotmc.org/resources/timingspatch-fix-the-timings-command.29217/

**Comment by RainOfPain125** [comment]
[18:08:43 ERROR]: Could not pass event ServerCommandEvent to TimingsPatcher v1.0 org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57] at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:471) [lt.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:433) [lt.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?] at java.lang.Thread.run(Unknown Source) [?:1.8.0_181] Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.spigot()Lorg/bukkit/Server$Spigot; at net.papucraft.plugins.TimingsPatch.Main.handle(Main.java:87) ~[?:?] at net.papucraft.plugins.TimingsPatch.Main.onServerCommand(Main.java:55) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57] ... 8 more [18:08:43 INFO]: View timings results can be viewed at http://www.spigotmc.org/go/timings?url=0

**Comment by electronicboy** [comment]
If the plugin doesn't work you'll need to speak to the plugin author/trying an older version of the plugin that might be more compatible with older versions of the server

**Comment by RainOfPain125** [comment]
I only has one version.. No github links, no profiles, just a 2 year old plugin. Guess I'm in the dust :(

**Comment by aikar** [comment]
Sorry but you would need to find someone else to make you a modified version for your needs then. I am not able to do that for you.
