### ISSUE TITLE
Minecraft Crash Report

### ISSUE THREAD

**Issue by Floxiii** [aikar/timings#68]
`Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at co.aikar.timings.TimingHistory$2$1.apply(TimingHistory.java:121)
	at co.aikar.timings.TimingHistory$2$1.apply(TimingHistory.java:1)
	at co.aikar.util.JSONUtil.toArrayMapper(JSONUtil.java:80)
	at co.aikar.util.JSONUtil.toArrayMapper(JSONUtil.java:74)
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:110)
	at co.aikar.timings.TimingHistory$2.apply(TimingHistory.java:1)
	at co.aikar.util.JSONUtil.toObjectMapper(JSONUtil.java:102)
	at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:105)
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:71)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:831)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:666)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by electronicboy** [comment]
This issue tracker is for issues with the timings website, not for issues with the implementation of timings in others software, especially versions which we haven't maintained in years; Speak to the author of your fork.
