### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by blank826** [aikar/timings#98]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/20/20 11:11 AM
Description: Exception in server tick loop

java.lang.ClassCastException: E£( cannot be cast to co.aikar.timings.TimingHandl
	at co.aikar.timings.TimingsManager.tick(TimingsManager.java:77)
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:51)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:835)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
	at java.lang.Thread.run(Unknown Source)

**Comment by aikar** [comment]
Not appropriate place to report errors like this, but we do not support the environment you are running. You have some bad plugin causing this. So you need to remove any plugin that touches timings.
